### ISSUE TITLE
Error when create project

### ISSUE THREAD

**Issue by keopx** [Metadrop/drupal-boilerplate#69] opened 2022-05-18 18:10 UTC
```
Do you want to continue? (yes/no) [yes]:

 > 

 [warning] Failed to drop or create the database. Do it yourself before installing. ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (-3)

 [notice] Starting Drupal installation. This takes a while.
 [notice] Performed install task: install_select_language
 [notice] Performed install task: install_select_profile
 [notice] Performed install task: install_load_profile

In install.core.inc line 2313:
                                                                               
  Database settings:<br /><br />Resolve all issues below to continue the inst  
  allation. For help configuring your database server, see the <a href="https  
  ://www.drupal.org/docs/8/install">installation handbook</a>, or contact you  
  r hosting provider.<div class="item-list"><ul><li>Failed to connect to your  
   database server. The server reports the following message: <em class="plac  
  eholder">SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo faile  
  d: Try again</em>.<ul><li>Is the database server running?</li><li>Does the   
  database exist or does the database user have sufficient privileges to crea  
  te the database?</li><li>Have you entered the correct database name?</li><l  
  i>Have you entered the correct username and password?</li><li>Have you ente  
  red the correct database hostname and port number?</li></ul></li></ul></div  
  >                                                                      
```

![image](https://user-images.githubusercontent.com/537583/169114636-6f19c51c-21b0-462a-95fe-cc9b56b41ef7.png)

**Comment by rsanzante** [comment] 2022-05-19 11:22
It seems this is the same issue as https://github.com/Metadrop/drupal-boilerplate/issues/68: no space left in device. In that case, I would expect more errors after the first failure, including not finding the MariaDB host (the DB container).

Can you check again with enough free space in the device?

**Comment by rsanzante** [comment] 2022-06-06 09:21
Closing this issue because @keopx  confirmed by other means that the problem was the space in device.

**Closed as completed by rsanzante** 2022-06-06 09:21 UTC
